# version: '3.7'
name: "dock-dev"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    depends_on:
      - php
    volumes:
      - ./nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html/
      - ./logs/:/var/log/nginx/

  php:
    build:
      context: ./php
    volumes:
      - ./php/conf.d/php.ini:/usr/local/etc/php/php.ini
      - ./html/:/var/www/html/
      - /var/www/html/vendor
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  mysql:
    # platform: linux/x86_64
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      # VIRTUAL_HOST: phpmyadmin.local
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 3000000000
    ports:
      - 8765:80
    depends_on:
      - mysql        
